version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: lms-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: f23rdocs1m01015/lms-backend:latest
    container_name: lms-backend
    restart: unless-stopped
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/lms
      JWT_SECRET: change_me
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:3000
      ALLOW_MEMORY_MONGO: "false"
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: f23rdocs1m01015/lms-frontend:latest
    container_name: lms-frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mongo-data: