apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: lms
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: lms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: f23rdocs1m01015/lms-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: lms-config
                  key: MONGO_URI
            - name: JWT_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: lms-config
                  key: JWT_EXPIRES_IN
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: lms-config
                  key: CORS_ORIGIN
            - name: ALLOW_MEMORY_MONGO
              valueFrom:
                configMapKeyRef:
                  name: lms-config
                  key: ALLOW_MEMORY_MONGO
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lms-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
