apiVersion: v1
kind: ConfigMap
metadata:
  name: lms-config
  namespace: lms
data:
  MONGO_URI: mongodb://mongo:27017/lms
  JWT_EXPIRES_IN: 7d
  CORS_ORIGIN: http://lms.local
  ALLOW_MEMORY_MONGO: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: lms-secrets
  namespace: lms
type: Opaque
stringData:
  JWT_SECRET: change-me-before-production
